spring.datasource.url=jdbc:h2:file:./data/onlinedb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.security.user.name=admin
spring.security.user.password=123456

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update

file.upload.directory=./uploads


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB